configserver:
  name: RNO Registry config server
  status: Connected to the RNO Registry config server!
  version: 1.0

info.description: Using Central Config
logging:
  level:
    com.hgicreate.rno: debug

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 30
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 40000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  serverListRefreshInterval: 5000

---

spring:
  profiles: uat
eureka:
  client.serviceUrl.defaultZone: http://192.168.6.41:8761/eureka/
logging:
  level:
    com.hgicreate.rno: debug

---

spring:
    profiles: prod
eureka:
    client.serviceUrl.defaultZone: http://192.168.50.20:8761/eureka/
logging:
  level:
    com.hgicreate.rno: debug
